from .paquets import RepartitionCaracteristiqueGlobale,RepartitionCaracteristiqueParCategorie,ColumnsList,plotHistogramGlobal,plotHistogrammeParType
from .adr import Proportion_ADR_Cat,RepartitionAdrGlobale
from .devices import nombreDevices